### PR TITLE
Complete (safe) rewrite of the derive macro

### PR DESCRIPTION
**Pull request by the10thWiz**
This PR provides an initial implementation of a safe derive macro for `Transient`.

## Features

- Multiple lifetimes
- `#[variance(...)]` is placed outside the struct
- Emits code that ensures the derived trait only compiles if the variance parameters are valid.

## Implementation

The new derive macro generates additional functions, which have a type signature that is only valid if the struct lifetimes have the specified variance.

```rust
#[derive(Transient)]
#[variance('a = co)]
struct SingleLife<'a> {
    val: &'a str,
}

// --- Generated: ---
unsafe impl<'a> Transient for SingleLife<'a> {
    type Static = SingleLife<'static>;
    type Transience = (Co<'a>);
}
#[allow(unused)]
#[allow(non_snake_case)]
fn __validate_SingleLife() {
    #[allow(unused)]
    #[allow(non_snake_case)]
    fn __validate_SingleLife_a<'__test_lifetime: 'a, 'a>(
        v: SingleLife<'__test_lifetime>,
    ) -> SingleLife<'a> {
        v
    }
}
```

If, for example, the member `val` was of type `fn(&'a str)`, the above code would fail to compile, since the lifetime `'a` would be contravariant, not covariant.

The primary downside to this approach is that the errors this produces are not easy to read, and provide unhelpful suggestions (since they recommend changing the type signature of the generated function), but I don't know any way to implement this safely without this issue.

## TODO

- [x] Implement improved derive macro
- [x] Ensure current tests compile (with new syntax)
- [x] Add additional tests to verify new functionality
- [x] Generate `Static` impl for types w/o a lifetime

### CODE REVIEW

**Comment by JRRudy1** [comment]
Hello again, thanks for working on this!

I like your idea of generating a check function to validate the requested variance; I knew it was pretty awkward how I was making the user declare "unsafe_covariant" and such to emphasize the unsafety of the decision, and hoped to find a better way such as manually inspecting the fields to detect the proper variance (which would be pretty difficult to do correctly for every possible scenario, so your approach is probably much more realistic).

Unfortunately I just pushed a significant refactor to the macro's implementation before seeing this PR, and will need to work on merging your idea into it. But the refactor should hopefully make integrating these kinds of improvements much easier than the sloppy initial implementation.

**Comment by the10thWiz** [comment]
I've just rebased (I've discarded all of your changes for the moment, I just wanted to get CI to run). Because of the somewhat messy implementation, I wound up just rewriting it from scratch.

It looks like the primary improvements you made was that a no-lifetimes struct now generates an impl of `Static` instead. This should be pretty simple to add, let me know if there are any other features that you added.

**Comment by the10thWiz** [comment]
> manually inspecting the fields to detect the proper variance

Like you, I'm not sure that this is possible in general. I think the easiest solution might be (once this is somewhat stabilized and proven) to propose upstreaming this into the standard library.

**Comment by JRRudy1** [comment]
> It looks like the primary improvements you made was that a no-lifetimes struct now generates an impl of Static instead.

Yes I think that is the only feature I added, and was mostly focused on cleaning up and refactoring the code to make it more readable and maintainable going forward. 

I would ideally like to merge our efforts instead of discarding my own since I do think there is value in the updates I made the layout/structure (although it certainly isn't perfect), but you did great work in adding a lot of missing features and I am eager to incorporate them after iterating a bit.

I am pretty busy with a work project at the moment so it will likely be a couple days before I can review your changes in depth, but I will get back to you ASAP. Thanks again!

**Comment by the10thWiz** [comment]
I've made some changes based on the changes you made, although I had already made a number of changes that aligned with yours. Thank you in advance for taking the time to look over my changes.

**Comment by JRRudy1** [comment]
@the10thWiz your changes look great, and I will merge them!

However I had some ideas for updating the syntax and implementation and ended up reworking my current version again taking heavy inspiration from yours, which I'd like to rebase back onto your updates, so sorry in advance for overwriting your efforts... I know this kind of thing is highly subjective and certainly don't mean to imply that my new-new version is definitively "better" than yours or anything. I will create a separate merge request for 4th iteration and would love to get your feedback on it.

I really do appreciate your interest and contribution to the project, and am excited that have found a solid use-case for it in the rocket framework :)

**Comment by the10thWiz** [comment]
> sorry in advance

Don't worry about it. I'm not particularly tied to my implementation, I'm really just looking to move towards a fully safe derive macro. I'm more than happy to take a look at whatever you come up with.

**Pull request merged**
